# main text of home
name: Sebiwi
bio: Tech, fun, and cookies
## Add "<h2 class="description">I solve problems at <a href="{{ site.workplace_site }}">{{ site.workplace }}</a>.</h2>" to headet.html when youre
## allowed to talk about your job again.
# workplace: Amazon Web Services
# workplace_site: https://aws.amazon.com/

# twitter summary info
description: Tech, fun and cookies

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/profile.jpg

# If you want to include your resume, set to true
# and specify source (external or local).
#resume: true
#resume-external: true
#resume-url: https://google.com/?q=my+resume

url: https://sebiwi.github.io
# your url: http://USERNAME.github.io

permalink: /:categories/:title/

# To enable google analytics, supply your token below
# analytics-google: 'UA-MYANALYTICS'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# Disqus, if you don't want comments in your posts, leave categories empty
disqus:
  shortname: sebiwi-github-io # enter this from your disqus account
  categories: [blog, project] # only show disqus for posts that have these categories

# Social media
#facebook: myfacebook
twitter: sebiwicb
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
# linkedin: mylinkedin
# youtube: myyoutube
# spotify: myspotify
github: sebiwi
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
#medium: medium
# vimeo: myvimeo
email: contact.sebiwi@gmail.com

authors:
    sebiwi:
        name: Sebiwi
        bio: Perfectionist
        external-image: false
        picture: assets/images/profile.jpg
        twitter: sebiwicb

# Width of the site
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# Pagination
# paginate: 5
# paginate_path: "blog/:num/"

# Active about, blog ,comics, and project sections
#about: true
blog: true
comics: true
#projects: true

# Show readtime
read-time: true

# Show tags
show-tags: true

# Show related posts
related: true

# Display links for next and previous posts for the specified categories
post-advance-links: [blog, comics]

# Show author block at the end of a post
show-author: true

# Animations \o/
animation: true

plugins:
  - jekyll-seo-tag
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

## Build
# Include .nojekyll file
include:
  - .nojekyll
